#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomerConsumer.Resource", IsApplication=true)]

namespace CustomerConsumer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AutoMapper.Android.Resource.String.ApplicationName = global::CustomerConsumer.Resource.String.ApplicationName;
			global::AutoMapper.Android.Resource.String.Hello = global::CustomerConsumer.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int big = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int huge = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int med = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int small = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int smallMed = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050023
			public const int LoginBTN = 2131034147;
			
			// aapt resource value: 0x7f05001a
			public const int LoginSubmitBTN = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int Password = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int PasswordText = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int UserName = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int UserNameText = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int addMe = 2131034126;
			
			// aapt resource value: 0x7f050021
			public const int addToCart = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int back = 2131034146;
			
			// aapt resource value: 0x7f050002
			public const int button2 = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int cartID = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int cartList = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int cartToGames = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int checkout = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int gameName = 2131034121;
			
			// aapt resource value: 0x7f05001e
			public const int genre = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int genreSearch = 2131034140;
			
			// aapt resource value: 0x7f050026
			public const int goToCart = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int goToGames = 2131034149;
			
			// aapt resource value: 0x7f05000a
			public const int itemPrice = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout2 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout4 = 2131034125;
			
			// aapt resource value: 0x7f050020
			public const int listOfGames = 2131034144;
			
			// aapt resource value: 0x7f05000c
			public const int numberPicker1 = 2131034124;
			
			// aapt resource value: 0x7f050024
			public const int outputText = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int radioGroup1 = 2131034141;
			
			// aapt resource value: 0x7f050004
			public const int relativeLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int space1 = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int space2 = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int space3 = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int subMe = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int tags = 2131034143;
			
			// aapt resource value: 0x7f050027
			public const int textView1 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int textView2 = 2131034152;
			
			// aapt resource value: 0x7f05001b
			public const int textView3 = 2131034139;
			
			// aapt resource value: 0x7f050014
			public const int textViewTest = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int textview = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int totalForCart = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int updateCart = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cart = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CartDetailsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DialogCheckoutLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DialogLoginLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Games = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GamesDetailsLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Temp = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Test = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
